services:
  - type: web
    name: working-days-api
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: working-days-db
          property: connectionString
      - key: HOLIDAY_CACHE_TTL_SECONDS
        value: 86400
      - key: HOLIDAY_API_URL
        value: "https://content.capta.co/Recruitment/WorkingDays.json"

databases:
  - name: working-days-db
    databaseName: working_days
    ipAllowList: []
    plan: free
